Member:
  extensions:
    - MemberExtension
BlogEntry:
  extensions:
    - BlogEntryMemberExtension
Blog_Controller:
  extensions:
    - Blog_ControllerExtension
Page_Controller:
  extensions:
    - SS_MinifiedResponseExtension