Member:
  extensions:
    - MemberExtension
BlogEntry:
  extensions:
    - BlogEntryMemberExtension
Blog_Controller:
  extensions:
    - Blog_ControllerExtension
Page_Controller:
  extensions:
    - SS_MinifiedResponseExtension
FilesystemPublisher:
    static_base_url: https://studentlife.uiowa.edu
---
Only:
  environment: live
---
Director:
  alternate_protocol: 'https'
---
Only:
  environment: dev
---
Director:
  alternate_protocol: 'http'